name: echemdb-converters
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - frictionless
  - isort
  - pandas
  - pip
  - pylint
  - pytest
  - pytest-doctestplus
  - pytest-xdist
  - pytest-remotedata