name: echemdb-converters
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  # - clevercsv
  - click>=8,<9
  - frictionless>=5,<6
  - isort
  - pandas
  - pip
  - pylint
  - pytest
  - pytest-doctestplus
  - pytest-xdist
  - pytest-remotedata
  - svgdigitizer
  - unitpackage
  - pip:
    - clevercsv>=0.7.4,<0.8.0
